spring:
  profiles:
    active: dev
  application:
    name: zuul-gateway
server:
  port: 43323
eureka:
  client:
    service-url:
      defaultZone: http://eureka10086.com:10086/eureka/
  instance:
    instance-id: gateway.com