server:
  port: 80
spring:
  datasource:
#   数据源基本配置
    username: root
    password: ENC(3eB+q2aWMZUuFAF4/uTCjyygRtDCkyi1)
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ttms?useUnicode=true&characterEncoding=gbk&useSSL=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8
    type: com.alibaba.druid.pool.DruidDataSource
  application:
    name: http-client
  profiles:
    active: dev
eureka:
  client:
    service-url:
      defaultZone: http://eureka10086.com:10086/eureka/
pagehelper:
  reasonable: true
mybatis:
  mapper-locations: classpath:mybatis/mapper/**/*.xml