

spring:
  datasource:
#   数据源基本配置
    username: root
    password: ENC(YfyxpJmnENdbi3b0KivVLDfXDBxJCizV)
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ttms?useUnicode=true&characterEncoding=gbk&useSSL=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8
    type: com.alibaba.druid.pool.DruidDataSource
#   数据源其他配置
    initialSize: 30
    minIdle: 30
    maxActive: 70
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
  application:
    name: provider-user
  profiles:
    active: dev

server:
  port: 12222
eureka:
  client:
    service-url:
      defaultZone: http://eureka10086.com:10086/eureka/
  instance:
    instance-id: provider-user
pagehelper:
  reasonable: true
mybatis:
  mapper-locations: classpath:mybatis/mapper/**/*.xml
  
auth-server: http://www.thesevensky.com:11111

security:
  oauth2:
    client:
      client-id: theSevenSky1
      client-secret: ENC(J7rvS+15xacoAGrim2n8uKIDpxj/Fkip)
      access-token-uri: ${auth-server}/oauth/token
      user-authorization-uri: ${auth-server}/oauth/authorize
    resource:
      token-info-uri: ${auth-server}/oauth/check_token







