spring:
  profiles:
    active: dev
  application:
    name: zuul-gateway
server:
  port: 6666
eureka:
  client:
    service-url:
      defaultZone: ENC(PU+TT5q5QlAYO/JAg8O+3pgiwkb0xieEGLc0XnR1Zd0OUGUrtuo6/V6SFBS9vEJb)
  instance:
    instance-id: gateway.com