
feign:
  hystrix:
    enabled: true
server:
  port: 8080
spring:
  application:
    name: http-client
  profiles:
    active: dev

eureka:
  client:
    service-url:
      defaultZone: http://eureka10086.com:10086/eureka/
pagehelper:
  reasonable: true

