
spring:
  datasource:
#   数据源基本配置
    username: root
    password: ENC(3eB+q2aWMZUuFAF4/uTCjyygRtDCkyi1)
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ttms?useUnicode=true&characterEncoding=gbk&useSSL=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8
    type: com.alibaba.druid.pool.DruidDataSource
#   数据源其他配置
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
  application:
    name: provider-user
  profiles:
    active: dev
server:
  port: 19527
eureka:
  client:
    service-url:
      defaultZone: http://eureka10086.com:10086/eureka/
pagehelper:
  reasonable: true
mybatis:
  mapper-locations: classpath:mybatis/mapper/**/*.xml

