


spring:
  datasource:
#   数据源基本配置
    username: root
    password: ENC(XWQIhdXApJR2zyhqKQ8h+IcWhFSjGUDs)
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:8066/ttms?useUnicode=true&characterEncoding=gbk&useSSL=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8
    type: com.alibaba.druid.pool.DruidDataSource
#   数据源其他配置
    initialSize: 30
    minIdle: 30
    maxActive: 70
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
  application:
    name: oauth2-server
  profiles:
    active: dev

server:
  port: 11111
eureka:
  client:
    service-url:
      defaultZone: http://eureka10086.com:10086/eureka/
  instance:
    instance-id: oauth2-server
pagehelper:
  reasonable: true
mybatis:
  mapper-locations: classpath:mybatis/mapper/**/*.xml








